-- Pacientes
create table pacientes (
  id bigint generated by default as identity primary key,
  nome text not null,
  cpf text,
  telefone text,
  data_nasc date,
  created_at timestamptz default now()
);

-- Destinos (clinicas/hospitais)
create table destinos (
  id bigint generated by default as identity primary key,
  nome text not null,
  cidade text,
  especialidade text,
  endereco text,
  telefone text,
  created_at timestamptz default now()
);

-- Motoristas
create table motoristas (
  id bigint generated by default as identity primary key,
  nome text not null,
  cnh text,
  telefone text,
  categoria_cnh text default 'B',
  created_at timestamptz default now()
);

-- Veiculos
create table veiculos (
  id bigint generated by default as identity primary key,
  placa text not null,
  modelo text,
  capacidade int default 5,
  tipo text,
  ano int,
  cor text,
  km_atual int default 0,
  combustivel text default 'Gasolina',
  consumo_medio numeric default 10,
  created_at timestamptz default now()
);

-- Admins
create table admins (
  id bigint generated by default as identity primary key,
  nome text not null,
  email text,
  cargo text,
  created_at timestamptz default now()
);

-- Viagens
create table viagens (
  id bigint generated by default as identity primary key,
  data date not null,
  horario_saida text,
  veiculo_id bigint references veiculos(id),
  motorista_id bigint references motoristas(id),
  status text default 'agendada',
  abastecimento jsonb,
  created_at timestamptz default now()
);

-- Passageiros da viagem
create table passageiros_viagem (
  id bigint generated by default as identity primary key,
  viagem_id bigint references viagens(id) on delete cascade,
  paciente_id bigint references pacientes(id),
  destino_id bigint references destinos(id),
  horario_chegada text,
  status text default 'indefinido',
  assinatura text,
  created_at timestamptz default now()
);

-- Dados iniciais: Pacientes
insert into pacientes (nome, cpf, telefone, data_nasc) values
  ('Maria Aparecida Silva',  '123.456.789-00', '(67) 99123-4567', '1958-04-12'),
  ('João Pedro Oliveira',    '234.567.890-11', '(67) 99234-5678', '1965-07-22'),
  ('Ana Claudia Ferreira',   '345.678.901-22', '(67) 99345-6789', '1972-01-05'),
  ('Carlos Eduardo Santos',  '456.789.012-33', '(67) 99456-7890', '1980-11-30'),
  ('Luiza Helena Costa',     '567.890.123-44', '(67) 99567-8901', '1950-03-18'),
  ('Antonio Jose Pereira',   '678.901.234-55', '(67) 99678-9012', '1945-09-01'),
  ('Rosaria Batista Lima',   '789.012.345-66', '(67) 99789-0123', '1963-06-14'),
  ('Francisco Alves Souza',  '890.123.456-77', '(67) 99890-1234', '1975-12-08');

-- Dados iniciais: Destinos
insert into destinos (nome, cidade, especialidade, endereco, telefone) values
  ('Hospital Regional de Campo Grande', 'Campo Grande', 'Geral',        'Av. Ceara, 3253',          '(67) 3312-1000'),
  ('HEMOSUL - Hemocentro',              'Campo Grande', 'Hematologia',  'Av. Fernando Correa, 1304', '(67) 3313-3700'),
  ('FUNSAU - Clinica Nefrologia',       'Campo Grande', 'Nefrologia',   'Rua Ceara, 1702',           '(67) 3314-0800'),
  ('Hospital do Cancer Alfredo Abrao',  'Campo Grande', 'Oncologia',    'Rua A. M. Coelho, 245',     '(67) 3329-9600'),
  ('Santa Casa de Campo Grande',        'Campo Grande', 'Cardiologia',  'Rua General Mello, 1580',   '(67) 3322-4000'),
  ('APAE Campo Grande',                 'Campo Grande', 'Reabilitacao', 'Rua Taquarussu, 261',       '(67) 3387-7700'),
  ('UDI Hospital',                      'Campo Grande', 'Ortopedia',    'Av. Mato Grosso, 1572',     '(67) 3041-7000'),
  ('Clinica de Olhos Visao+',           'Campo Grande', 'Oftalmologia', 'Rua 26 de Agosto, 503',     '(67) 3383-0000');

-- Dados iniciais: Motoristas
insert into motoristas (nome, cnh, telefone, categoria_cnh) values
  ('Roberto Mendes',      '12345678900', '(67) 99111-2222', 'D'),
  ('Paulo Henrique Dias', '98765432100', '(67) 99333-4444', 'B'),
  ('Sonia Maria Ramos',   '11122233344', '(67) 99555-6666', 'D');

-- Dados iniciais: Veiculos
insert into veiculos (placa, modelo, capacidade, tipo, ano, cor, km_atual, combustivel, consumo_medio) values
  ('ABC-1234', 'Fiat Doblo',          5,  'Carro',       2022, 'Branco', 45200, 'Etanol',   12),
  ('DEF-5678', 'VW Spin',             7,  'Van Pequena', 2021, 'Prata',  78300, 'Gasolina', 10),
  ('GHI-9012', 'Mercedes Sprinter',   15, 'Van Grande',  2023, 'Branco', 32100, 'Diesel',   9),
  ('JKL-3456', 'Micro-onibus Volare', 21, 'Micro-onibus',2020, 'Branco', 96500, 'Diesel',   7);

-- Dados iniciais: Admins
insert into admins (nome, email, cargo) values
  ('Secretaria Ana Paula', 'ana@saude.gov.br', 'Coordenadora');

-- Politicas de acesso publico (para testes sem autenticacao)
alter table pacientes enable row level security;
alter table destinos enable row level security;
alter table motoristas enable row level security;
alter table veiculos enable row level security;
alter table admins enable row level security;
alter table viagens enable row level security;
alter table passageiros_viagem enable row level security;

create policy "acesso publico pacientes"        on pacientes        for all using (true) with check (true);
create policy "acesso publico destinos"         on destinos         for all using (true) with check (true);
create policy "acesso publico motoristas"       on motoristas       for all using (true) with check (true);
create policy "acesso publico veiculos"         on veiculos         for all using (true) with check (true);
create policy "acesso publico admins"           on admins           for all using (true) with check (true);
create policy "acesso publico viagens"          on viagens          for all using (true) with check (true);
create policy "acesso publico passageiros"      on passageiros_viagem for all using (true) with check (true);
