-- Tabela de pedidos de transferencia entre motoristas
create table if not exists transferencias (
  id bigint generated by default as identity primary key,
  passageiro_id bigint references passageiros_viagem(id) on delete cascade,
  viagem_origem_id bigint references viagens(id) on delete cascade,
  viagem_destino_id bigint references viagens(id) on delete cascade,
  motorista_origem_id bigint references motoristas(id),
  motorista_destino_id bigint references motoristas(id),
  status text default 'pendente',
  created_at timestamptz default now()
);

alter table transferencias enable row level security;

drop policy if exists "acesso publico transferencias" on transferencias;
create policy "acesso publico transferencias"
  on transferencias
  for all
  using (true)
  with check (true);
